blog/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.post_list, name="post_list"),
    path('blog/', views.post_list, name="post_list"),
    path('recipes_search/', views.post_list, name="recipes_search"),
    path("create_post/", views.create_blog_post, name="create_post"),
    path('like/<int:pk>/', views.post_like, name="post_like"),
    path('edit_comment/<int:pk>/',
         views.edit_blog_comment, name='edit_blog_comment'
         ),
    path('delete_comment/<int:pk>/',
         views.delete_blog_comment,
         name='delete_blog_comment'
         ),
    path('<int:pk>/', views.post_detail, name="post_detail"),
    path("<int:pk>/edit", views.edit_blog_post, name="edit_blog_post"),
    path("<int:pk>/delete",
         views.delete_blog_post, name="delete_blog_post"
         ),
]

indian_tuin/urls.py
from django.contrib import admin
from django.urls import path, include
from menu.views import handler404, handler500, handler403
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('restaurant.urls')),
    path('blog/', include('blog.urls'), name='blog'),
    path('summernote/', include('django_summernote.urls')),
    path('menu/', include('menu.urls')),
    path("accounts/", include("allauth.urls")),
    path("users/", include("users.urls")),
]
urlpatterns += [
        path('404/', handler404),
        path('500/', handler500),
        path('403/', handler403),
    ]

restaurant/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('reservations/', views.reservations, name='reservations'),
    path(
        'reservations/user/',
        views.user_reservations,
        name='user_reservations'
        ),
    path('reservations/user/<int:pk>',
         views.edit_user_reservation, name='editReservations'
         ),
    path('reservations/user/<int:pk>/delete',
         views.delete_user_reservation, name='deleteReservations'
         ),
    path('reservations/success/',
         views.reservations_success, name='reservations_success'
         ),

]

restaurant/models.py
from django.db import models
from cloudinary.models import CloudinaryField


class Photo(models.Model):
    """
    Creates a table in the database which stores photos"
    """
    title = models.CharField(max_length=150)
    image = CloudinaryField('image', default='placeholder')

    def __str__(self):
        return self.title


class Reservation(models.Model):
    """
    Reservation model class.
    Creates a table in the database which stores each objects data"
    """
    name = models.CharField(max_length=100, null=True, blank=True)
    email = models.EmailField()
    number_of_persons = models.PositiveSmallIntegerField(choices=(
        (1, '1'),
        (2, '2'),
        (3, '3'),
        (4, '4'),
        (5, '5'),
        (6, '6'),
        (7, '7'),
        (8, '8'),
        (9, '9'),
        (10, '10'),
    ), null=True)
    date = models.DateField()
    time = models.PositiveSmallIntegerField(choices=(
        (1, '11:00-12:00'),
        (2, '12:00-13:00'),
        (3, '13:00-14:00'),
        (4, '14:00-15:00'),
        (5, '16:00-17:00'),
        (6, '18:00-19:00'),
        (7, '20:00-21:00'),
    ), null=True)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.name) + " " + str(self.date)

    class Meta:
        """
        The Reservation model Meta class.
        Defines that each instance is ordered by earliest date.
        """
        ordering = ['-date']

restaurant/forms.py
from django import forms
from django.utils import timezone
from django.core.exceptions import ValidationError
from .models import Reservation
from django.forms import TextInput
from django.core.validators import EmailValidator


class DateInput(forms.DateInput):
    """
    This class defines to select date with the help of datepicker
    """
    input_type = 'date'


class ReservationForm(forms.ModelForm):
    """
    This defines the user form output for the
    Reservation model class
    """

    class Meta:
        """
        Meta class defines the associated models and
        the fields accessible to the user.
        """
        model = Reservation
        fields = [
            'name',
            'email',
            'number_of_persons',
            'date',
            'time'
        ]
        widgets = {
            'date': DateInput(),
            'name': forms.TextInput(
                attrs={
                    'required': True,
                    "class": "form-control",
                    "pattern": "[A-Za-z ]+",
                    "title": "Name can only contain letters",
                }
            ),
            'email': forms.TextInput(
                attrs={
                    'required': True,
                    "class": "form-control",
                    "pattern": '[a-z0-9._%+-]+@[a-z0-9.-]+.[a-z]{2,}$',
                    "title": "Please enter a valid email address",
                }
            ),
                  }

    # Disable the past dates in date input widget
    date = forms.DateField(widget=forms.DateInput(attrs={
        'type': 'date', 'min': timezone.localdate().strftime('%Y-%m-%d')
        }))

    def clean(self):
        """
        Validates the date and time fields to ensure
        a user is not allowed to book a reservation
        for today after the current time.
        """
        cleaned_data = super().clean()
        chosen_date = cleaned_data.get("date")
        chosen_time = cleaned_data.get("time")
        if chosen_date == timezone.now().date() and chosen_time:
            current_hour = timezone.now().hour
            earliest_hour = {
                1: 11,
                2: 12,
                3: 13,
                4: 14,
                5: 16,
                6: 18,
                7: 20,
            }.get(chosen_time)
            if current_hour >= earliest_hour:
                raise forms.ValidationError(
                    "Reservation cannot be booked today after current time"
                    )
        return cleaned_data

restaurant/views.py
from datetime import datetime
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .models import Photo, Reservation
from .forms import ReservationForm
from django.contrib.auth import get_user_model


def handler404(request, exception):
    return render(request, 'error/404.html', status=404)


def handler500(request):
    return render(request, 'error/500.html', status=500)


def home(request):
    """
    This view will render the images of the home page.
    """
    about_image = Photo.objects.get(title='about_image')
    context = {
        'about_image': about_image}
    return render(request, 'restaurant/index.html', context)


User = get_user_model()


def reservations(request):
    """
    This view will render the reservations page
    """
    time_image = Photo.objects.get(title='Times Image')
    if request.user.is_authenticated:
        form = ReservationForm()
        if request.method == 'POST':
            form = ReservationForm(request.POST)
            date = form['date'].value()
            date_value = datetime.strptime(date, "%Y-%m-%d")
            time = form['time'].value()
            reservation = Reservation.objects. \
                filter(date=date_value, time=time)
            # Check if the restaurant is closed on Mondays
            if date_value.weekday() == 0:
                messages.warning(request,
                                 'Sorry, the restaurant is closed on Mondays.'
                                 )

                return redirect('reservations')
            if reservation:
                messages.warning(
                    request,
                    'Reservation already exists at this date and time.'
                    'Please choose another date and time'
                    )
                return redirect('reservations')
            if form.is_valid():
                form.save()
                messages.success(request, 'Reservation created successfully.')
                return redirect('reservations_success')
            else:
                messages.error(request, f'Some details are missing/wrong.')
        context = {
            'time_image': time_image,
            'form': form
        }
        return render(request, 'restaurant/reservations.html', context)
    else:
        form = ReservationForm()
        if request.method == 'POST':
            form = ReservationForm(request.POST)
            if form.is_valid():
                date = form['date'].value()
                date_value = datetime.strptime(date, "%Y-%m-%d")
                time = form['time'].value()
                email = form['email'].value()
                reservation = Reservation.objects. \
                    filter(date=date_value, time=time)
                # Check if the restaurant is closed on Mondays
                if date_value.weekday() == 0:
                    messages.warning(request,
                                     'Sorry, the restaurant closed on Mondays.'
                                     )

                    return redirect('reservations')
                if reservation:
                    messages.warning(
                        request,
                        'Reservation already exists at this date and time.'
                        'Please choose another date and time'
                        )
                    return redirect('reservations')
                reservation = Reservation.objects.create(
                    date=date_value,
                    time=time,
                    email=email
                )
                reservation.save()
                messages.success(request, 'Reservation created successfully.')
                return redirect('reservations_success')
            else:
                messages.error(request, f'Some details are missing/wrong.')
        context = {'time_image': time_image, 'form': form}
        return render(request, 'restaurant/reservations.html', context)


def reservations_success(request):
    """
    This view will render the reservations success page
    """
    return render(request, 'restaurant/reservations_success.html')


@login_required
def edit_user_reservation(request, pk):
    """
    This view allows the user to edit reservations.
    """
    reservation = Reservation.objects.get(id=pk)
    form = ReservationForm(instance=reservation)

    if request.method == 'POST':
        form = ReservationForm(
            request.POST, request.FILES, instance=reservation
            )
        if form.is_valid():
            date = form.cleaned_data['date']
            time = form.cleaned_data['time']
            # Check if there is already a reservation for this date and time
            if Reservation.objects.filter(date=date, time=time).exists():
                messages.warning(
                 request,
                 'Reservation already exists at this date and time.'
                 'Please choose another date and time'
                )
                return redirect('user_reservations')

            # Check if the restaurant is closed on Mondays
            if date.weekday() == 0:
                messages.warning(
                    request,
                    'Sorry, the restaurant is closed on Mondays.'
                    )
                return redirect('user_reservations')

            # Save the reservation if everything is valid
            form.save()
            messages.success(request, 'Reservation Updated.')
            return redirect('user_reservations')

    context = {'form': form}
    return render(request, 'restaurant/edit_reservation.html', context)


@login_required
def delete_user_reservation(request, pk):
    """
    This view allows the user to delete reservations.
    """
    reservation = Reservation.objects.get(id=pk)

    if request.method == 'POST':
        reservation.delete()
        messages.success(request, 'Reservation has been deleted.')
        redirect('user_reservations')

    context = {'reservation': reservation}
    return render(request, 'restaurant/delete_reservation.html', context)


@login_required
def user_reservations(request):
    """
    This view allows the user to see their reservations.
    """

    reservations = Reservation.objects.all()

    if request.user.is_staff:
        user_reservations = reservations.order_by('date')
        if not user_reservations:
            messages.warning(request, 'No Reservations Booked At This Time.')
            return render(request, 'users/profile.html')
    else:
        user_reservations = reservations.filter(
            email=request.user.email
            ).order_by('date')
        if not user_reservations:
            messages.warning(request, 'No Reservations Found For This Email.')
            return render(request, 'users/profile.html')
    context = {'reservations': user_reservations}
    messages.success(request, 'Reservations Found.')
    return render(request, 'restaurant/user_reservations.html', context)

restaurant/templates/restaurant/delete_reservation.html
{% extends 'base.html' %}
{% block content %}
<h1 class="create-form">Delete Reservation</h1>
<div class="delete-desc">
    <h3>Are you sure you want to delete this booking?</h3>
    <p>Please note: The applied changes are <strong>PERMANENT</strong>!</p>
</div>
<form class="create-form" method="POST">
    {% csrf_token %}

    <a href="{% url 'user_reservations' %}" class="btn primary form-button">Go
            Back</a>
    <button type="submit" class="form-button">Delete</button>

</form>
</div>
{% endblock %}

restaurant/templates/restaurant/edit_reservation.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load cloudinary %}
{% block content %}
<h1 class="create-form">Reservation Form</h1>
<form class="create-form" id="edit-reserve-form" action="#" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form | crispy }}

    <button type="button" class="form-button">
        <a href="{% url 'reservations' %}" class="back-link">Go Back</a>
      </button>
      
      <button type="submit" class="form-button">Submit</button>
      

</form>

{% endblock %}

restaurant/templates/restaurant/index.html
{% extends 'base.html' %}
{% block content %}
<!-- Banner section -->
<section id="home" class="banner_wrapper">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-5 text-center text-lg-start order-lg-1 order-2">
                <h1><span>INDIAN TUIN RESTAURANT</span><br></h1>
                <p><i>A treat for your taste buds!!</i></p>
                <a class="main-btn mt-4" href="{% url 'menu' %}">View Menu</a>
            </div>
        </div>
        <!-- About section -->
        <section id="about" class="about_wrapper">
            <div class="container">
                <div class="row">
                    <div class="col-xl-4 col-lg-5 mb-4 mb-lg-0 order-lg-1 order-2">
                        <div class="card rounded-0">
                            <div class="card-body pt-5">
                                <h3>Welcome to Our Restaurant</h3>
                                <p>We create a finest taste of Indian cuisines and we also offer a perfect
                                    place to enjoy meal together with your family and friends.
                                </p>

                                <a href="{% url 'reservations' %}" class="main-btn mt-4">Book a Table
                                </a>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-8 col-lg-7 mb-4 mb-lg-0 order-lg-2 order-1">
                        <img loading="lazy" src="{{about_image.image.url}}" class="img-fluid" alt="About Us">
                    </div>

                </div>
            </div>
        </section>
    </div>
</section>
<!-- About section exit -->
{% endblock %}

restaurant/templates/restaurant/reservations.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<h1 class="reservation-title">Reservations</h1>
<div class="container-fluid">
    <div class="row">
      <div class="col-md-6">
        <form class="col-md-12 mx-auto" action="{% url 'reservations' %}" method="post" enctype="multipart/form-data">

            {% csrf_token %}
            {{ form | crispy }}

            <div class="d-flex justify-content-center button-row">
                <button type="submit" class="reserve-button" id="book-now-btn">Book Now</button>
                {% if user.is_authenticated %}
                <a href="{% url 'user_reservations' %}" class="reserve-button"
                    id="reserve-link">Update Booking
                </a>
                {% endif %}
            </div>
        </form>
    </div>
    <div class="side-image">
        <img src="{{ time_image.image.url }}" id="open-times-image" class="time-image" alt="an image displaying the open times for the restaurant">
    </div>
</div>
</div>
{% endblock %}

restaurant/templates/restaurant/reservations_success.html
{% extends 'base.html' %}
{% block content %}
<div class="container mt-5">
  <div class="row justify-content-center">
      <div class="col-md-8">
          <div class="card">
              <div class="card-header">
                  <h4 class="success-booking">Booking Successful!</h4>
              </div>
              <div class="card-body">
                  <p>Your booking has been confirmed.</p>
                  <p>Thank you for choosing our service.</p>
                  <p class="text-danger">Please note: Please login to edit your reservations</p>
                  <p class="text-primary">Unregistered users have to contact us to update or cancel their booking. </p>
                  <p>Please contact us at:</p>
                  <ul class="list-group">
                    <li class="list-group-item"><b>Address:</b> 18 Angelenhorst, 2171, Sassenheim</li>
                    <li class="list-group-item"><b>Phone:</b> <span class="badge bg-primary">+31 123 08 4567</span></li>
                    <li class="list-group-item"><b>Email:</b> <span class="badge bg-primary">indian_ tuin@gmail.com</span></li>
                  </ul>
                  <a href="{% url 'home' %}" class="btn primary home-button">Back to Home</a>
              </div>
          </div>
      </div>
  </div>
</div>

{% endblock %}

restaurant/templates/restaurant/user_reservations.html
{% extends 'base.html' %}
{% block content %}
<h1 class="reserve-title">Your Reservations</h1>
<p class="reserve-p">You can view and edit your reservations below.</p>
{% if reservations %}
<table class="table table-hover table-bordered" class="reservations-table">
    <thead class="table-head">
        <tr>
            <th>#</th>
            {% if user.is_staff %}
            <th>Name</th>
            {% endif %}
            <th>Date</th>
            <th>Time</th>
            <th>Update</th>
            <th>Delete</th>
        </tr>
    </thead>
    <tbody class="table-group-divider table-body">
        {% for reservation in reservations %}
        <tr>
            <td>{{ forloop.counter }}</td>
            {% if user.is_staff %}
            <td>{{ reservation.name }}</td>
            {% endif %}
            <td>{{ reservation.date }}</td>
            <td>{{ reservation.get_time_display }}</td>
            <td><a href="{% url 'editReservations' reservation.id %}"><i class="fa-solid fa-pen-to-square"></i></a></td>
            <td><a href="{% url 'deleteReservations' reservation.id %}"><i class="fa-solid fa-trash-can"></i></a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endif %}
{% endblock %}