blog/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.post_list, name="post_list"),
    path('blog/', views.post_list, name="post_list"),
    path('recipes_search/', views.post_list, name="recipes_search"),
    path("create_post/", views.create_blog_post, name="create_post"),
    path('like/<int:pk>/', views.post_like, name="post_like"),
    path('edit_comment/<int:pk>/',
         views.edit_blog_comment, name='edit_blog_comment'
         ),
    path('delete_comment/<int:pk>/',
         views.delete_blog_comment,
         name='delete_blog_comment'
         ),
    path('<int:pk>/', views.post_detail, name="post_detail"),
    path("<int:pk>/edit", views.edit_blog_post, name="edit_blog_post"),
    path("<int:pk>/delete",
         views.delete_blog_post, name="delete_blog_post"
         ),
]

indian_tuin/urls.py
from django.contrib import admin
from django.urls import path, include
from menu.views import handler404, handler500, handler403
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('restaurant.urls')),
    path('blog/', include('blog.urls'), name='blog'),
    path('summernote/', include('django_summernote.urls')),
    path('menu/', include('menu.urls')),
    path("accounts/", include("allauth.urls")),
    path("users/", include("users.urls")),
]
urlpatterns += [
        path('404/', handler404),
        path('500/', handler500),
        path('403/', handler403),
    ]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField

STATUS = ((0, "Draft"), (1, "Published"))


class Post(models.Model):
    """
    This model class defines all the fields in the class.
    Creates a table in the database which stores each objects data.
    """
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="blog_posts"
    )
    featured_image = CloudinaryField('image', default='placeholder')
    excerpt = models.TextField(blank=True)
    meal_type = models.PositiveSmallIntegerField(choices=(
        (1, 'starter'),
        (2, 'main'),
        (3, 'dessert'),
    ), null=True)
    food_type = models.PositiveSmallIntegerField(choices=(
        (1, 'rice'),
        (2, 'bread and rotis'),
        (3, 'meat'),
        (4, 'fish'),
        (5, 'drinks'),
        (6, 'sweet'),
        (7, 'seafood'),
        (8, 'vegetarian'),
        ), null=True)
    updated_on = models.DateTimeField(auto_now=True)
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)
    likes = models.ManyToManyField(
        User, related_name='blogpost_like', blank=True)

    class Meta:
        """
    The Post model meta class defines the occurence of instances.
    It also defines the string representation of the post class.
    """
        ordering = ["-created_on"]

    def __str__(self):
        return self.title

    def number_of_likes(self):
        return self.likes.count()


class Comment(models.Model):
    """
    The Comment model class defines all the fields in the class.
    It creates a table in the database which stores each objects data.
    """
    post = models.ForeignKey(Post, on_delete=models.CASCADE,
                             related_name="comments")
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)

    class Meta:
        """
    The Comment model meta class defines the occurence of instances.
    It also defines the string representation of the Comment class.
    """

    ordering = ["created_on"]

    def __str__(self):
        return f"Comment {self.body} by {self.name}"

blog/forms.py
from django import forms
from django.forms import ModelForm
from django_summernote.widgets import SummernoteWidget
from .models import Post, Comment


class PostForm(ModelForm):
    """
    The PostForm class defines the user form output for the Post model class.
    """
    content = forms.CharField(widget=SummernoteWidget())

    class Meta:
        """
        The Meta class defines which model is associated and from that model,
        which fields will be accessible to the user.
        """
        model = Post
        fields = (
            'title',
            'featured_image',
            'excerpt',
            'meal_type',
            'food_type',
            'content'
        )


class CommentForm(forms.ModelForm):
    """
    The CommentForm class defines the user form output for the
    Comment model class.
    """
    class Meta:
        """
        The Meta class defines which model is associated and from that model,
        which fields will be accessible to the user.
        """
        model = Comment
        fields = ('body',)

blog/views.py
"""
Importing libraries to use in system.
"""
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.core.paginator import Paginator
from django.http import HttpResponseRedirect
from django.db.models import Count
from django.contrib import messages
from .models import Post, Comment
from .forms import CommentForm, PostForm


def post_list(request):
    """
    This view is to render the blog page and all the posts.
    This view limits the posts to 2 per page.
    """
    post_list = Post.objects.all()
    comments = Post.objects.annotate(post_comments=Count('comments')) \
        .order_by('-post_comments')[:3]

    paginator = Paginator(post_list, 2)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'post_list': post_list,
        'page_obj': page_obj,
    }
    return render(
        request, 'blog/post_list.html', context)


def post_detail(request, pk):
    """
    This view is to render single blog post.
    This view allows the user to like and unlike the posts.
    Registered users can leave comments.
    """
    post_detail = Post.objects.all()
    post = get_object_or_404(Post, id=pk)
    comments = post.comments.filter(approved=True).order_by("-created_on")
    liked = False
    if post.likes.filter(id=request.user.id).exists():
        liked = True

    comment_form = CommentForm(data=request.POST)
    if comment_form.is_valid():
        comment_form.instance.email = request.user.email
        comment_form.instance.name = request.user.username
        comment = comment_form.save(commit=False)
        comment.post = post
        comment.save()
        messages.success(
                    request, 'Comment awaiting approval.'
                    )
    else:
        comment_form = CommentForm()
    context = {
        'post': post,
        'liked': liked,
        "comment_form": CommentForm(),
        'commented': True,
        'comments': comments,
        'comment_form': comment_form,
    }
    return render(request, 'blog/post_detail.html', context)


def post_like(request, pk):
    """
    This view allows users to like or unlike a blog post.
    """
    if request.user.is_authenticated:
        post = get_object_or_404(Post, id=request.POST.get('post_id'))
        liked = False
        if post.likes.filter(id=request.user.id).exists():
            post.likes.remove(request.user)
            liked = False
        else:
            post.likes.add(request.user)
            liked = True

        return HttpResponseRedirect(reverse('post_detail', args=[str(pk)]))

    else:
        messages.warning(
            request,
            'You have to log in!'
        )
        return redirect('account_login')


def create_blog_post(request):
    """
    This view to render a form to create new blog posts.
    """
    form = PostForm()

    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, 'Post Created.')
            return redirect("post_detail", pk=pk)

    context = {'form': form}
    return render(request, 'blog/create_post.html', context)


def edit_blog_post(request, pk):
    """
    This view to render a form to edit existing blog posts.
    """
    post = get_object_or_404(Post, pk=pk)
    form = PostForm(instance=post)

    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            form.save()
            messages.success(request, f'{post.title} Updated.')
            return redirect("post_detail", pk=pk)

    context = {'post': post, 'form': form}
    return render(request, 'blog/edit_post.html', context)


def delete_blog_post(request, pk):
    """
    This view is to delete blog posts.
    """
    post = get_object_or_404(Post, pk=pk)

    if request.method == "POST":
        post.delete()
        messages.success(request, f'Post is deleted.')
        return redirect("post_list")

    context = {"post": post}

    return render(request, "blog/delete_post.html", context,)


def edit_blog_comment(request, pk):
    """
    This view is to edit commment on a blog post.
    """
    comment = get_object_or_404(Comment, id=pk)
    post = comment.post.id
    form = CommentForm(instance=comment)
    if request.method == 'POST':
        form = CommentForm(request.POST, request.FILES, instance=comment)
        if form.is_valid():
            form.save()
            messages.success(request, 'Comment is updated.')
            return redirect(f'/blog/{post}')

    context = {'post': comment, 'form': form, }
    return render(request, 'blog/edit_comment.html', context)


def delete_blog_comment(request, pk):
    """
    This view is to delete commment on a blog post.
    """
    comment = get_object_or_404(Comment, pk=pk)
    post = comment.post.id

    if request.method == 'POST':
        comment.delete()
        messages.success(request, f'Comment is deleted.')
        return redirect(f'/blog/{post}')

    context = {'post': comment}
    return render(request, 'blog/delete_comment.html', context)

blog/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<main>
    <section class="section">
        <div class="container">
            <div class="col-12">
                <h1 class="page-title">{{ post.title }}</h1>
                <p class="home-description">{{ post.excerpt }}</p>
                <div class="col-md-4 sidebar ftco-animate pt-3">
                    <div class="sidebar-box pt-md-4">
                        <form action="{% url 'post_list' %}" method="POST" class="search-form" id="recipes-search">
                            {% csrf_token %}

                            <div class="input-group mb-3">
                                <input type="search" name="recipe_name" id="recipe-input" class="form-control"
                                    placeholder="Enter Recipe Here..." aria-label="Recipe Name"
                                    aria-describedby="button-addon2">
                                <button class="btn btn-outline-secondary" type="submit" id="button-addon2"><i
                                        class="fa-solid fa-magnifying-glass"></i></button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>

            <div class="col-md-8 mb-5 mb-lg-0">
                <div class="col-12 mb-4">
                    <div class="card article-card">
                        <div class="card-image">
                            <div class="post-info"> <span class="text-uppercase">{{ post.datepublished }}</span>
                            </div>
                            <img loading="lazy" decoding="async" src="{{ post.featured_image.url }}"
                                alt="Post Thumbnail" class="w-100">
                        </div>
                        <div class="card-body px-0 pb-1">
                            <ul class="post-meta mb-2">
                                <li>
                                    {{ post.get_meal_type_display|capfirst }} </li>,

                                <li> {{ post.get_food_type_display }}
                                </li>
                            </ul>
                            <div class="meta-wrap" id="post-meta">
                                <form action="{% url 'post_like' post.slug %}" method="POST">
                                    {% csrf_token %}
                                    <p class="meta">
                                        <span><i class="fa-solid fa-calendar-days"></i>{{ post.created_on }}</span>
                                        <span><i class="fa-solid fa-user-pen"></i>{{ post.author}}</span>

                                        <button type="submit" name="post_id" value="{{ post.id }}"><i
                                                class="fa-solid fa-heart"></i></button>{{ post.number_of_likes}}

                                    </p>
                                </form>
                            </div>
                        </div>

                        {% if user.is_staff %}
                        <div class="blog-post-buttons">
                            <a href="{% url 'edit_blog_post' post.slug %}"><button type="submit"
                                    class="reserve-button">Edit</button></a>
                            <a href="{% url 'delete_blog_post' post.slug %}"><button type="submit"
                                    class="reserve-button">Delete</button></a>
                        </div>
                        {% endif %}
                        <div class="main-description">{{  post.content|safe  }}
                        </div>

                        <div class="row">
                            <div class="col">
                                <hr>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-8 card mb-4  mt-3 ">
                            <h3 class="main-comment">Comments:</h3>
                            <div class="card-body">
                                {% for comment in comments %}
                                {% if commented %}

                                <div class="comments" style="padding: 10px;">
                                    <p class="font-weight-bold">
                                        {{ comment.name }}
                                        <span class=" text-muted font-weight-normal">
                                            {{ comment.created_on }}
                                        </span> wrote:
                                        {% if comment.author|stringformat:'s' == request.user.username|stringformat:'s' or user.is_staff %}
                                        <span> <a href="{% url 'edit_blog_comment' post.slug %}"
                                                class="btn btn-success comment-button">Edit</a>
                                            <a href="{% url 'delete_blog_comment' post.slug %}"
                                                class="btn btn-danger comment-button">Delete</a></span>
                                        {% endif %}
                                    </p>
                                    {{ comment.body | linebreaks }}
                                </div>
                                {% if user.is_authenticated %}
                                <span> <a href="{% url 'edit_blog_comment' post.id %}"
                                        class="btn btn-success comment-button">Edit</a>
                                    <a href="{% url 'delete_blog_comment' post.id %}"
                                        class="btn btn-danger comment-button">Delete</a></span>
                                {% endif %}
                            </div>
                            {% endif %}
                            {% endfor %}
                        </div>
                        <div class="col-md-4 card mb-4 mt-3 ">

                            <div class="card-body">

                                {% if user.is_authenticated %}

                                <h3 class="comment-head">Leave a comment:</h3>
                                <p>Posting as: {{ user.username }}</p>
                                <form method="post" style="margin-top: 1.3em;">
                                    {{ comment_form | crispy }}
                                    {% csrf_token %}
                                    <button type="submit" class="submit-btn">Submit</button>
                                </form>

                                {% endif %}

                            </div>
                        </div>
                    </div>
</main>
{% endblock %}

blog/templates/posts/post_list.html
{% extends 'base.html' %}
{% block content %}
<main>
    <section class="section">
        <div class="container">
            <div class="row no-gutters-lg">
                <div class="col-12">
                    <h1 class="page-title">Our Recipe Blog</h1>
                    <p class="blog-description"><i><b>Finest taste of Indian cuisine at your home.</i></p>
                </div>
                <div class="col-md-4 sidebar ftco-animate pt-5">
                    <div class="sidebar-box pt-md-4">
                        <form action="{% url 'post_list' %}" method="POST" class="search-form" id="recipes-search">
                            {% csrf_token %}

                            <div class="form-group fg--search">


                                <input type="search" name="recipe_name" id="recipe-input" class="form-control"
                                    placeholder="Enter Recipe Here..." aria-label="Recipe Name"
                                    aria-describedby="button-addon2">
                                <button type="submit"><i class="fa fa-search"></i></button>
                            </div>
                        </form>
                    </div>
                </div>

                {% for post in page_obj %}
                <div class="col-8 mb-4">
                    <div class="card article-card">
                        <a href="{% url 'post_list' %}">
                            <div class="card-image">
                                <div class="post-info"> <span class="text-uppercase">{{ post.datepublished }}</span>
                                </div>
                                <img loading="lazy" decoding="async" src="{{ post.featured_image.url }}"
                                    alt="Post Thumbnail" class="w-100">
                            </div>
                        </a>
                        <div class="card-body px-0 pb-1">
                            <ul class="post-meta mb-2">
                                <li> {{ post.get_meal_type_display| capfirst }} </li>,

                                <li> {{ post.get_food_type_display| capfirst }}</li>

                            </ul>
                            <div class="meta-wrap">
                                <p class="meta">
                                    <span><i class="fa-solid fa-calendar-days"></i>{{ post.created_on }}</span>
                                    <span><i class="fa-solid fa-user-pen"></i>{{ post.author}}</span>
                                    <span><i class="fa-solid fa-heart"></i>{{ post.number_of_likes}}</span>


                                </p>
                            </div>
                            <h2 class="h1">{{ post.title }}</h2>
                            <p class="card-text">{{ post.excerpt }}</p>
                            <div class="content"> <a class="read-more-btn" href="{% url 'post_detail' post.slug %}">Read
                                    More</a>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>

        <div class="pagination p-links">
            <span class="step-links">
                {% if page_obj.has_previous %}
                <a href="?page=1" class="page">&laquo</a>
                <a href="?page={{ page_obj.previous_page_number }}"></a>
                {% endif %}

                <span class="current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
                </span>

                {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}"></a>
                <a href="?page={{ page_obj.paginator.num_pages }}" class="page">&raquo;</a>
                {% endif %}
            </span>
        </div>
    </section>
</main>
{% endblock %}